# Generated by Django 6.0 on 2025-12-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselTmage',
            new_name='CarouselImage',
        ),
    ]
